#if UNITY_EDITOR
using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEngine.UI;using UnityEngine.XR.ARFoundation;using UnityEngine.XR.ARSubsystems;using Unity.XR.CoreUtils;
[InitializeOnLoad] public static class ARShowroomSetup{
 static string scene="Assets/ARCarShowroom/Scenes/ARCarShowroom.unity"; static ARShowroomSetup(){EditorApplication.delayCall+=Setup;}
 static void Setup(){if(System.IO.File.Exists(scene))return;System.IO.Directory.CreateDirectory("Assets/ARCarShowroom/Scenes");var sc=EditorSceneManager.NewScene(NewSceneSetup.EmptyScene,NewSceneMode.Single);new GameObject("AR Session").AddComponent<ARSession>();var rig=new GameObject("XR Origin (Mobile AR)");var xo=rig.AddComponent<XROrigin>();var pm=rig.AddComponent<ARPlaneManager>();var rm=rig.AddComponent<ARRaycastManager>();var camgo=new GameObject("AR Camera");camgo.transform.SetParent(rig.transform,false);camgo.tag="MainCamera";var cam=camgo.AddComponent<Camera>();camgo.AddComponent<AudioListener>();xo.Camera=cam;var fac=new GameObject("Car Factory").AddComponent<CarFactory>();var car=CarFactory.Build();System.IO.Directory.CreateDirectory("Assets/ARCarShowroom/Prefabs");var prefab=PrefabUtility.SaveAsPrefabAsset(car,"Assets/ARCarShowroom/Prefabs/ARShowroomCar.prefab");Object.DestroyImmediate(car);Object.DestroyImmediate(fac.gameObject);var ind=GameObject.CreatePrimitive(PrimitiveType.Cylinder);ind.name="Placement Indicator";ind.transform.localScale=new Vector3(.8f,.01f,.8f);Object.DestroyImmediate(ind.GetComponent<Collider>());ind.SetActive(false);var man=new GameObject("AR Placement Manager").AddComponent<ARPlacementManager>();man.raycastManager=rm;man.arCamera=cam;man.carPrefab=prefab;man.placementIndicator=ind;MakeUI(man);EditorSceneManager.SaveScene(sc,scene);AssetDatabase.Refresh();}
 static void MakeUI(ARPlacementManager man){var c=new GameObject("UI Canvas").AddComponent<Canvas>();c.renderMode=RenderMode.ScreenSpaceOverlay;c.gameObject.AddComponent<CanvasScaler>().uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;c.gameObject.AddComponent<GraphicRaycaster>();var ui=c.gameObject.AddComponent<ARShowroomUI>();ui.placement=man;ui.status=Text(c.transform,"Move camera to scan a floor, then tap to place the car.",22,new Vector2(.05f,.86f),new Vector2(.95f,.98f));string[] names={"COLOR","DOORS","LIGHTS","ENGINE","INFO","RESET"};for(int i=0;i<6;i++){var b=Button(c.transform,names[i],new Vector2(i/6f,.02f),new Vector2((i+1)/6f,.16f));int k=i;if(i==0)b.onClick.AddListener(ui.Color);if(i==1)b.onClick.AddListener(ui.Doors);if(i==2)b.onClick.AddListener(ui.Lights);if(i==3)b.onClick.AddListener(ui.Engine);if(i==4)b.onClick.AddListener(ui.Info);if(i==5)b.onClick.AddListener(ui.Reset);}}
 static Text Text(Transform p,string s,float size,Vector2 a,Vector2 b){var g=new GameObject("Text");g.transform.SetParent(p,false);var t=g.AddComponent<Text>();t.text=s;t.fontSize=(int)size;t.color=Color.white;t.alignment=TextAnchor.MiddleCenter;var r=t.rectTransform;r.anchorMin=a;r.anchorMax=b;r.offsetMin=r.offsetMax=Vector2.zero;return t;}
 static Button Button(Transform p,string s,Vector2 a,Vector2 b){var g=new GameObject(s);g.transform.SetParent(p,false);var im=g.AddComponent<Image>();im.color=new Color(.05f,.15f,.28f,.92f);var bt=g.AddComponent<Button>();var t=Text(g.transform,s,18,Vector2.zero,Vector2.one);t.rectTransform.offsetMin=t.rectTransform.offsetMax=Vector2.zero;var r=bt.GetComponent<RectTransform>();r.anchorMin=a;r.anchorMax=b;r.offsetMin=new Vector2(3,0);r.offsetMax=new Vector2(-3,0);return bt;}
}
#endif
